[app_servers]
app-server ansible_host=172.16.0.2

[mon_servers]
mon-server ansible_host=172.16.0.3

[log_servers]
log-server ansible_host=172.16.0.4

[cluster:children]
app_servers
mon_servers
log_servers

[cluster:vars]
ansible_user=auto_user
ansible_port=3927
ansible_ssh_private_key_file="{{ lookup('env', 'HOME') }}/.ssh/ansible-key"
ansible_python_interpreter=/usr/bin/python3
