# Stage 3: Install docker engine, compose, configure access users
---
- name: Install and configure docker for user
  hosts: cluster
  become: yes
  tasks:
    - name: Install dependencies
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
          - gnupg
        state: present 
    
    - name: Create keyrings directory
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Add gpg key in to keyring file
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'

    - name: Add docker repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

    - name: Install docker
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        update_cache: true
        cache_valid_time: 3600

    - name: Add devops and auto_user in docker group
      ansible.builtin.user:
        name: "{{ item }}"
        groups: docker
        append: yes
        state: present
      loop:
        - devops
        - auto_user
